/* =============================================================
   True North NPK - progressive image loading
   -------------------------------------------------------------
   Works hand-in-hand with js/img-manifest.js (generated by
   tools/optimize_images.py). For every image the site shows it:

     1. Reserves the image's space up front  -> no layout jump
        (the "wireframe" stage).
     2. Paints a tiny blurred placeholder instantly on the frame
        (the "blurred" stage, for images marked .lqip-img).
     3. Upgrades the file to WebP where the browser supports it.
     4. Fades the sharp image in once it has decoded
        (the "high quality" stage), and lazy-loads anything
        below the fold so the server isn't hammered up front.

   It also watches the DOM, so images the page builds with
   JavaScript (nav badge, album art, member cards, home preview)
   get the same treatment automatically.

   Progressive enhancement: if this script never runs, every
   image still shows normally - nothing is hidden without JS.
   ============================================================= */
(function () {
  "use strict";

  var M = window.IMG_MANIFEST || {};
  var docEl = document.documentElement;

  /* Marks that the enhancer is live, so the CSS only hides .lqip-img
     images (to fade them in) when we're actually able to reveal them. */
  docEl.classList.add("tn-img");

  var WEBP = supportsWebp();

  function supportsWebp() {
    try {
      var c = document.createElement("canvas");
      return c.toDataURL("image/webp").indexOf("data:image/webp") === 0;
    } catch (e) { return false; }
  }

  /* Map an <img>'s src back to a manifest key (handles relative,
     absolute and %-encoded URLs from the photos page). */
  function lookup(img) {
    var raw = img.getAttribute("src");
    if (!raw) return null;
    var path;
    try { path = decodeURIComponent(new URL(raw, document.baseURI).pathname); }
    catch (e) { path = decodeURIComponent(raw); }
    var i = path.indexOf("assets/img/");
    return i < 0 ? null : (M[path.slice(i)] || null);
  }

  function reveal(img) { img.classList.add("tn-loaded"); }

  function enhance(img) {
    if (img.__tn) return;          /* process each image once */
    img.__tn = 1;

    var isLqip = img.classList.contains("lqip-img");
    var entry = lookup(img);

    if (!entry) { if (isLqip) reveal(img); return; }   /* never leave one hidden */

    /* 1. reserve space (prevents layout shift) */
    if (!img.hasAttribute("width"))  img.setAttribute("width", entry.w);
    if (!img.hasAttribute("height")) img.setAttribute("height", entry.h);

    /* 2. decode off the main thread; lazy-load unless flagged eager */
    if (!img.getAttribute("decoding")) img.decoding = "async";
    if (img.hasAttribute("data-eager")) {
      img.loading = "eager";
      img.setAttribute("fetchpriority", "high");
    } else if (!img.getAttribute("loading")) {
      img.loading = "lazy";
    }

    /* 3. blur-up placeholder painted on the surrounding frame */
    if (isLqip && entry.lqip) {
      var frame = img.parentElement;
      if (frame) {
        frame.classList.add("tn-frame");
        frame.style.setProperty("--tn-lqip", 'url("' + entry.lqip + '")');
      }
    }

    /* 4. upgrade to WebP */
    if (WEBP && entry.webp) img.src = entry.webp;

    /* 5. fade the sharp image in once ready */
    if (img.complete && img.naturalWidth) {
      reveal(img);
    } else {
      img.addEventListener("load",  function () { reveal(img); }, { once: true });
      img.addEventListener("error", function () { reveal(img); }, { once: true });
    }
  }

  function scan(node) {
    if (!node) return;
    if (node.tagName === "IMG") { enhance(node); return; }
    if (node.querySelectorAll) {
      var imgs = node.querySelectorAll("img");
      for (var i = 0; i < imgs.length; i++) enhance(imgs[i]);
    }
  }

  /* catch images injected later by the page scripts */
  if (window.MutationObserver) {
    new MutationObserver(function (muts) {
      for (var i = 0; i < muts.length; i++) {
        var nodes = muts[i].addedNodes;
        for (var j = 0; j < nodes.length; j++) {
          if (nodes[j].nodeType === 1) scan(nodes[j]);
        }
      }
    }).observe(docEl, { childList: true, subtree: true });
  }

  /* initial sweep of whatever is already in the document */
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", function () { scan(document.body); });
  } else {
    scan(document.body);
  }
})();
